disable other builds and tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,5 +1,9 @@
 name: ci
-on: [ push, pull_request ]
+# on: [ push, pull_request ]
+on:
+  push:
+    tags:
+      - v*
 
 jobs:
   lint:
@@ -73,14 +77,14 @@ jobs:
             rustc: "1.75.0"
             extra_desc: dist-server
             extra_args: --no-default-features --features=dist-tests test_dist_ -- --test-threads 1
-          - os: ubuntu-20.04
-            rustc: stable
-          - os: ubuntu-20.04
-            rustc: beta
-          - os: ubuntu-20.04
-            rustc: nightly
-            allow_failure: true
-            extra_args: --features=unstable
+          # - os: ubuntu-20.04
+          #   rustc: stable
+          # - os: ubuntu-20.04
+          #   rustc: beta
+          # - os: ubuntu-20.04
+          #   rustc: nightly
+          #   allow_failure: true
+          #   extra_args: --features=unstable
           - os: ubuntu-20.04
             extra_desc: no-default-features
             extra_args: --no-default-features
@@ -93,41 +97,41 @@ jobs:
             # Oldest supported version, keep in sync with README.md
             rustc: "1.75.0"
             extra_desc: cuda12.6
-          - os: macos-13
-          # # M1 CPU
-          - os: macos-14
+          # - os: macos-13
+          # # # M1 CPU
+          # - os: macos-14
           - os: windows-2019
             cuda: "11.8"
             # Oldest supported version, keep in sync with README.md
             rustc: "1.75.0"
             extra_args: --no-fail-fast
             extra_desc: cuda11.8
-          - os: windows-2019
-            cuda: "11.8"
-            rustc: nightly
-            allow_failure: true
-            extra_args: --features=unstable
-            extra_desc: cuda11.8
-          - os: windows-2019
-            cuda: "11.8"
-            rustc: beta
-            extra_desc: cuda11.8
+          # - os: windows-2019
+          #   cuda: "11.8"
+          #   rustc: nightly
+          #   allow_failure: true
+          #   extra_args: --features=unstable
+          #   extra_desc: cuda11.8
+          # - os: windows-2019
+          #   cuda: "11.8"
+          #   rustc: beta
+          #   extra_desc: cuda11.8
           - os: windows-2022
             cuda: "12.6"
             # Oldest supported version, keep in sync with README.md
             rustc: "1.75.0"
             extra_args: --no-fail-fast
             extra_desc: cuda12.6
-          - os: windows-2022
-            cuda: "12.6"
-            rustc: nightly
-            allow_failure: true
-            extra_args: --features=unstable
-            extra_desc: cuda12.6
-          - os: windows-2022
-            cuda: "12.6"
-            rustc: beta
-            extra_desc: cuda12.6
+          # - os: windows-2022
+          #   cuda: "12.6"
+          #   rustc: nightly
+          #   allow_failure: true
+          #   extra_args: --features=unstable
+          #   extra_desc: cuda12.6
+          # - os: windows-2022
+          #   cuda: "12.6"
+          #   rustc: beta
+          #   extra_desc: cuda12.6
     env:
       RUST_BACKTRACE: 1
     steps:
@@ -201,24 +205,24 @@ jobs:
             extra_args: --no-default-features --features="dist-server"
             target: aarch64-unknown-linux-musl
             container: '{"image": "messense/rust-musl-cross:aarch64-musl"}'
-          - os: ubuntu-20.04
-            target: armv7-unknown-linux-musleabi
-            container: '{"image": "messense/rust-musl-cross:armv7-musleabi"}'
-          - os: ubuntu-20.04
-            target: i686-unknown-linux-musl
-            container: '{"image": "messense/rust-musl-cross:i686-musl"}'
-          - os: macos-13
-            target: x86_64-apple-darwin
-            macosx_deployment_target: 10.13
-          - os: macos-14
-            target: aarch64-apple-darwin
-            macosx_deployment_target: 11.0
+          # - os: ubuntu-20.04
+          #   target: armv7-unknown-linux-musleabi
+          #   container: '{"image": "messense/rust-musl-cross:armv7-musleabi"}'
+          # - os: ubuntu-20.04
+          #   target: i686-unknown-linux-musl
+          #   container: '{"image": "messense/rust-musl-cross:i686-musl"}'
+          # - os: macos-13
+          #   target: x86_64-apple-darwin
+          #   macosx_deployment_target: 10.13
+          # - os: macos-14
+          #   target: aarch64-apple-darwin
+          #   macosx_deployment_target: 11.0
           - os: windows-2019
             target: x86_64-pc-windows-msvc
             rustflags: -Ctarget-feature=+crt-static
-          - os: windows-2019
-            target: aarch64-pc-windows-msvc
-            rustflags: -Ctarget-feature=+crt-static
+          # - os: windows-2019
+          #   target: aarch64-pc-windows-msvc
+          #   rustflags: -Ctarget-feature=+crt-static
     steps:
       - name: Clone repository
         uses: actions/checkout@v4
@@ -253,143 +257,143 @@ jobs:
           path: target/${{ matrix.target }}/release/${{ matrix.binary || 'sccache' }}${{ endsWith(matrix.target, '-msvc') && '.exe' || '' }}
           if-no-files-found: error
 
-  coverage:
-    name: coverage ${{ matrix.os }} rust ${{ matrix.rustc || 'stable' }} ${{ matrix.extra_desc }}
-    runs-on: ${{ matrix.os }}
-    continue-on-error: ${{ matrix.allow_failure || false }}
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - os: ubuntu-22.04
-            cuda: "11.8"
-            rustc: nightly
-            allow_failure: true
-            extra_args: --features=unstable
-          - os: macos-13
-            rustc: nightly
-    # Disable on Windows for now as it fails with:
-    # found invalid metadata files for crate `vte_generate_state_changes`
-    #          - os: windows-2019
-    #            rustc: nightly
-    env:
-      RUST_BACKTRACE: 1
-    steps:
-      - name: Clone repository
-        uses: actions/checkout@v4
+  # coverage:
+  #   name: coverage ${{ matrix.os }} rust ${{ matrix.rustc || 'stable' }} ${{ matrix.extra_desc }}
+  #   runs-on: ${{ matrix.os }}
+  #   continue-on-error: ${{ matrix.allow_failure || false }}
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - os: ubuntu-22.04
+  #           cuda: "11.8"
+  #           rustc: nightly
+  #           allow_failure: true
+  #           extra_args: --features=unstable
+  #         - os: macos-13
+  #           rustc: nightly
+  #   # Disable on Windows for now as it fails with:
+  #   # found invalid metadata files for crate `vte_generate_state_changes`
+  #   #          - os: windows-2019
+  #   #            rustc: nightly
+  #   env:
+  #     RUST_BACKTRACE: 1
+  #   steps:
+  #     - name: Clone repository
+  #       uses: actions/checkout@v4
 
-      - name: Install rust
-        uses: ./.github/actions/rust-toolchain
-        with:
-          toolchain: ${{ matrix.rustc }}
+  #     - name: Install rust
+  #       uses: ./.github/actions/rust-toolchain
+  #       with:
+  #         toolchain: ${{ matrix.rustc }}
 
-      - name: Install gcc & clang for tests
-        run: sudo apt-get install -y clang gcc
-        if: ${{ matrix.os == 'ubuntu-20.04' }}
+  #     - name: Install gcc & clang for tests
+  #       run: sudo apt-get install -y clang gcc
+  #       if: ${{ matrix.os == 'ubuntu-20.04' }}
 
-      - if: matrix.cuda != '' && contains(fromJSON('["Linux", "Windows"]'), runner.os)
-        name: Install nvcc
-        uses: ./.github/actions/nvcc-toolchain
-        with:
-          cuda-version: ${{ matrix.cuda }}
+  #     - if: matrix.cuda != '' && contains(fromJSON('["Linux", "Windows"]'), runner.os)
+  #       name: Install nvcc
+  #       uses: ./.github/actions/nvcc-toolchain
+  #       with:
+  #         cuda-version: ${{ matrix.cuda }}
 
-      - name: "`grcov` ~ install"
-        run: cargo install grcov
+  #     - name: "`grcov` ~ install"
+  #       run: cargo install grcov
 
-      - name: Execute tests
-        run: cargo test --no-fail-fast --locked --all-targets ${{ matrix.extra_args }}
-        env:
-          CARGO_INCREMENTAL: "0"
-          RUSTC_WRAPPER: ""
-          RUSTFLAGS: "-Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Cprofile-generate=target/debug"
+  #     - name: Execute tests
+  #       run: cargo test --no-fail-fast --locked --all-targets ${{ matrix.extra_args }}
+  #       env:
+  #         CARGO_INCREMENTAL: "0"
+  #         RUSTC_WRAPPER: ""
+  #         RUSTFLAGS: "-Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Cprofile-generate=target/debug"
 
-      - name: Generate coverage data (via `grcov`)
-        id: coverage
-        shell: bash
-        run: |
-          ## Generate coverage data
-          COVERAGE_REPORT_DIR="target/debug"
-          COVERAGE_REPORT_FILE="${COVERAGE_REPORT_DIR}/lcov.info"
-          # GRCOV_IGNORE_OPTION='--ignore build.rs --ignore "/*" --ignore "[a-zA-Z]:/*"' ## `grcov` ignores these params when passed as an environment variable (why?)
-          # GRCOV_EXCLUDE_OPTION='--excl-br-line "^\s*((debug_)?assert(_eq|_ne)?!|#\[derive\()"' ## `grcov` ignores these params when passed as an environment variable (why?)
-          mkdir -p "${COVERAGE_REPORT_DIR}"
-          # display coverage files
-          grcov . --output-type files --ignore build.rs --ignore "/*" --ignore "[a-zA-Z]:/*" --excl-br-line "^\s*((debug_)?assert(_eq|_ne)?!|#\[derive\()" | sort --unique
-          # generate coverage report
-          grcov . --output-type lcov --output-path "${COVERAGE_REPORT_FILE}" --branch --ignore build.rs --ignore "/*" --ignore "[a-zA-Z]:/*" --excl-br-line "^\s*((debug_)?assert(_eq|_ne)?!|#\[derive\()"
-          echo "report=${COVERAGE_REPORT_FILE}" >> $GITHUB_OUTPUT
+  #     - name: Generate coverage data (via `grcov`)
+  #       id: coverage
+  #       shell: bash
+  #       run: |
+  #         ## Generate coverage data
+  #         COVERAGE_REPORT_DIR="target/debug"
+  #         COVERAGE_REPORT_FILE="${COVERAGE_REPORT_DIR}/lcov.info"
+  #         # GRCOV_IGNORE_OPTION='--ignore build.rs --ignore "/*" --ignore "[a-zA-Z]:/*"' ## `grcov` ignores these params when passed as an environment variable (why?)
+  #         # GRCOV_EXCLUDE_OPTION='--excl-br-line "^\s*((debug_)?assert(_eq|_ne)?!|#\[derive\()"' ## `grcov` ignores these params when passed as an environment variable (why?)
+  #         mkdir -p "${COVERAGE_REPORT_DIR}"
+  #         # display coverage files
+  #         grcov . --output-type files --ignore build.rs --ignore "/*" --ignore "[a-zA-Z]:/*" --excl-br-line "^\s*((debug_)?assert(_eq|_ne)?!|#\[derive\()" | sort --unique
+  #         # generate coverage report
+  #         grcov . --output-type lcov --output-path "${COVERAGE_REPORT_FILE}" --branch --ignore build.rs --ignore "/*" --ignore "[a-zA-Z]:/*" --excl-br-line "^\s*((debug_)?assert(_eq|_ne)?!|#\[derive\()"
+  #         echo "report=${COVERAGE_REPORT_FILE}" >> $GITHUB_OUTPUT
 
-      - name: Upload coverage results (to Codecov.io)
-        uses: codecov/codecov-action@v4
-        with:
-          file: ${{ steps.coverage.outputs.report }}
-          ## flags: IntegrationTests, UnitTests, ${{ steps.vars.outputs.CODECOV_FLAGS }}
-          flags: ${{ steps.vars.outputs.CODECOV_FLAGS }}
-          name: codecov-umbrella
-          fail_ci_if_error: false
+  #     - name: Upload coverage results (to Codecov.io)
+  #       uses: codecov/codecov-action@v4
+  #       with:
+  #         file: ${{ steps.coverage.outputs.report }}
+  #         ## flags: IntegrationTests, UnitTests, ${{ steps.vars.outputs.CODECOV_FLAGS }}
+  #         flags: ${{ steps.vars.outputs.CODECOV_FLAGS }}
+  #         name: codecov-umbrella
+  #         fail_ci_if_error: false
 
-  test_freebsd:
-    name: test freebsd-14.1 rust stable
-    runs-on: ${{ matrix.job.os }}
-    timeout-minutes: 70
-    strategy:
-      fail-fast: false
-      matrix:
-        job:
-          - { os: ubuntu-22.04 }
-    steps:
-      - uses: actions/checkout@v4
-      - name: Prepare, build and test
-        uses: vmactions/freebsd-vm@v1
-        with:
-          mem: 8192
-          usesh: true
-          sync: rsync
-          copyback: false
-          prepare: pkg install -y ca_root_nss curl gmake gtar pot sudo
-          run: |
-            #####################################################################################
-            ###  Prepare, build, and test
-            #####################################################################################
-            ###  based on ref: <https://github.com/rust-lang/rustup/pull/2783>
-            ###  and on ref: <https://github.com/uutils/coreutils/commit/86c610a84b8b6c>
-            ###  * NOTE: All steps need to be run in this block, otherwise, we are operating back
-            ###    on the mac host.
-            set -exo pipefail
-            #
-            ### Basic user setup ################################################################
-            TEST_USER=tester
-            TEST_USER_HOME="/opt/$TEST_USER"
-            REPO_NAME=${GITHUB_WORKSPACE##*/}
-            WORKSPACE_PARENT="/home/runner/work/${REPO_NAME}"
-            WORKSPACE="${WORKSPACE_PARENT}/${REPO_NAME}"
-            export WORKSPACE
-            #
-            mkdir -p "$TEST_USER_HOME"
-            pw adduser -n "$TEST_USER" -d "$TEST_USER_HOME" -c "Tester" -h -
-            chown -R "$TEST_USER":"$TEST_USER" "$TEST_USER_HOME"
-            chown -R "$TEST_USER":"$TEST_USER" "/$WORKSPACE_PARENT"/
-            cat > /usr/local/etc/sudoers.d/wheel<<EOF
-            $TEST_USER ALL=(ALL) NOPASSWD: ALL
-            EOF
-            #
-            ### Install rust stable from rustup  ################################################
-            su "$TEST_USER" -c "/bin/sh -exo pipefail" <<"EOH"
-            whoami
-            echo "$HOME"
-            fetch -o /tmp/rustup.sh https://sh.rustup.rs
-            sh /tmp/rustup.sh -y --profile=minimal
-            ### Run tests #######################################################################
-            . "$HOME/.cargo/env"
-            "$WORKSPACE/scripts/freebsd-ci-test.sh"
-            EOH
-            # end
-      - name: Upload failure
-        if: failure()
-        uses: ./.github/actions/artifact_failure
-        with:
-          name: test-freebsd-14.1-stable
+  # test_freebsd:
+  #   name: test freebsd-14.1 rust stable
+  #   runs-on: ${{ matrix.job.os }}
+  #   timeout-minutes: 70
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       job:
+  #         - { os: ubuntu-22.04 }
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Prepare, build and test
+  #       uses: vmactions/freebsd-vm@v1
+  #       with:
+  #         mem: 8192
+  #         usesh: true
+  #         sync: rsync
+  #         copyback: false
+  #         prepare: pkg install -y ca_root_nss curl gmake gtar pot sudo
+  #         run: |
+  #           #####################################################################################
+  #           ###  Prepare, build, and test
+  #           #####################################################################################
+  #           ###  based on ref: <https://github.com/rust-lang/rustup/pull/2783>
+  #           ###  and on ref: <https://github.com/uutils/coreutils/commit/86c610a84b8b6c>
+  #           ###  * NOTE: All steps need to be run in this block, otherwise, we are operating back
+  #           ###    on the mac host.
+  #           set -exo pipefail
+  #           #
+  #           ### Basic user setup ################################################################
+  #           TEST_USER=tester
+  #           TEST_USER_HOME="/opt/$TEST_USER"
+  #           REPO_NAME=${GITHUB_WORKSPACE##*/}
+  #           WORKSPACE_PARENT="/home/runner/work/${REPO_NAME}"
+  #           WORKSPACE="${WORKSPACE_PARENT}/${REPO_NAME}"
+  #           export WORKSPACE
+  #           #
+  #           mkdir -p "$TEST_USER_HOME"
+  #           pw adduser -n "$TEST_USER" -d "$TEST_USER_HOME" -c "Tester" -h -
+  #           chown -R "$TEST_USER":"$TEST_USER" "$TEST_USER_HOME"
+  #           chown -R "$TEST_USER":"$TEST_USER" "/$WORKSPACE_PARENT"/
+  #           cat > /usr/local/etc/sudoers.d/wheel<<EOF
+  #           $TEST_USER ALL=(ALL) NOPASSWD: ALL
+  #           EOF
+  #           #
+  #           ### Install rust stable from rustup  ################################################
+  #           su "$TEST_USER" -c "/bin/sh -exo pipefail" <<"EOH"
+  #           whoami
+  #           echo "$HOME"
+  #           fetch -o /tmp/rustup.sh https://sh.rustup.rs
+  #           sh /tmp/rustup.sh -y --profile=minimal
+  #           ### Run tests #######################################################################
+  #           . "$HOME/.cargo/env"
+  #           "$WORKSPACE/scripts/freebsd-ci-test.sh"
+  #           EOH
+  #           # end
+  #     - name: Upload failure
+  #       if: failure()
+  #       uses: ./.github/actions/artifact_failure
+  #       with:
+  #         name: test-freebsd-14.1-stable
 
   release:
     name: release
